### ISSUE TITLE
Android App: Going to Scan QR, then using the back button leaves the camera showing behind the list of albums

### ISSUE THREAD

**Issue by BillButter** [thelinkin3000/SonicLair#1]
![Screenshot_20220616-213414_SonicLair](https://user-images.githubusercontent.com/63459838/174204781-b088e637-6a37-41bb-a51e-4fd8521a88a5.png)

**Comment by thelinkin3000** [comment]
Hi!
The camera never stops appearing on the background? Or does it go away at some point?

**Comment by BillButter** [comment]
It takes about 5 seconds, but it does stop.

**Comment by thelinkin3000** [comment]
Thanks for reporting the issue!
I just triggered a new release, please update the app as it fixes pretty nasty bugs.
